[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = cmsis
upload_protocol = stlink
monitor_port = COM31
monitor_speed = 115200
build_flags =
  -D STM32F10X_MD
  -D USE_STDPERIPH_DRIVER
  -I include